// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwa-VVMC_aF5tQCAKTyFhnJuKWJIFbdYc',
    appId: '1:605711901872:web:6b4f2cc85784e63b600775',
    messagingSenderId: '605711901872',
    projectId: 'eventaura-8bf9c',
    authDomain: 'eventaura-8bf9c.firebaseapp.com',
    storageBucket: 'eventaura-8bf9c.firebasestorage.app',
    measurementId: 'G-GM8TTJ5DBT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAcX3nvtIZIDNwvbR2xOe46mtDoOHq9vs',
    appId: '1:605711901872:android:a1f4c5c903ceb8b3600775',
    messagingSenderId: '605711901872',
    projectId: 'eventaura-8bf9c',
    storageBucket: 'eventaura-8bf9c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-MJgb8xpEB6kT7yiilMpbt_rjUOohPGM',
    appId: '1:605711901872:ios:dd13c683d9722237600775',
    messagingSenderId: '605711901872',
    projectId: 'eventaura-8bf9c',
    storageBucket: 'eventaura-8bf9c.firebasestorage.app',
    iosClientId: '605711901872-2tbojqahra8qec66uns39ncsgshuagrj.apps.googleusercontent.com',
    iosBundleId: 'com.eventaura.app.eventauraFlutter',
  );
}
